stages:
  prepare:
    cmd: python src/preprocessing.py
    deps:
      - ../songs_normalize.csv
      - src/preprocessing.py
    outs:
      - data/pipeline.pkl
      - data/processed_train_data.csv
      - data/processed_test_data.csv
