apiVersion: apps/v1
kind: Deployment
metadata:
  name: redditapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redditapp
  template:
    metadata:
      labels:
        app: redditapp
    spec:
      containers:
        - name: redditapp
          image: redditapp:v1
          ports:
            - containerPort: 8000
